TITLE to add from 1 to 100 and display in hexadecimal form
.MODEL SMALL
.STACK 32
.DATA
NUM DB 0
CHECK DB 0

.CODE
MAIN PROC FAR
MOV AX,@DATA
MOV DS,AX

MOV CX,64H
MOV AX,0
STEP1:ADD AX,CX
LOOP STEP1

MOV NUM,AH
MOV SI, OFFSET NUM
MOV BX,16      ;for dividing the number by 16
MOV CX,0
STEP2:MOV DX,0
DIV BX           ;DIVIDES AX:DX BY BX AND REMAINDER IS IN DX ,QUOTIENT IS IN AX
CMP DX, 0H
JB NEXT
CMP DX, 09H
JA NEXT        
ADD DX,30H     ;converting into ascii character
JMP NEXT2
NEXT:CMP DX,0AH
JB NEXT2
CMP DX,0FH
JA NEXT2
ADD DX,37H           ;ADDING 37H TO THE REMAINDER DX
NEXT2:PUSH DX        ;storing in stack
INC CX
CMP AX,0         ;QUOTIENT       
JNE STEP2

;DISPLAY the stored decimal digits
LAST:MOV AH, 02
DISP:POP DX
INT 21H
LOOP DISP

MOV AH,4CH
INT 21H

MAIN ENDP
END MAIN
