LIST=integer*

PREDICATES
SELECTIVEDISPLAY(LIST,LIST)
UPDATE(LIST,LIST,LIST)
REVERSE(LIST,LIST,LIST)

CLAUSES 
SELECTIVEDISPLAY(A, B):- 
	UPDATE(A,[],TEMP), REVERSE(TEMP,[],B).
	UPDATE([], A, A).

UPDATE([H|T], A, B):- 
	H<3,H>0, UPDATE(T,[H|A], B).
	
UPDATE([H|T], A, B):-
	H<=0, UPDATE(T,A,B).
	
UPDATE([H|T], A, B):- 
	H>=3, UPDATE(T,A,B).
	REVERSE([],A,A).

REVERSE([H|T], A, R):-
	REVERSE(T, [H|A], R).

GOAL
SELECTIVEDISPLAY([1,1,2,3,4,1,1],X).
