%SOURCE CODE
PREDICATES
	POMPEIANS(STRING)
	ROMANS(STRING)
	LOYAL(STRING, STRING)
	PEOPLE(STRING)
	RULER(STRING)
	TRY_ASSASSINATE(STRING,STRING)
	HATED(STRING, STRING)

CLAUSES
	POMPEIANS("MARCUS").
	ROMANS(X) :- POMPEIANS(X).
	ROMANS(X) :- LOYAL("CAESER", X) ; HATED("CAESER", X).
	PEOPLE(X).
	RULER(Y).
	HATED(X,Y).
	LOYAL(Y,X).
	TRY_ASSASSINATE("MARCUS", "CAESER").
	TRY_ASSASSINATE(X,Y):- PEOPLE(X), RULER(Y), not(LOYAL(Y, X)).
	
GOAL
	HATED("CAESER", "MARCUS").

