PREDICATES
PEOPLE(STRING)
SMART(STRING)
HAPPY(STRING)
CAN_READ(STRING)
WEALTHY(STRING)
EXCITING_LIFE(STRING)

CLAUSES
	PEOPLE("JOHN").
	WEALTHY("JOHN").
	HAPPY(X) :- PEOPLE(X) , WEALTHY(X) , SMART(X).
	
	CAN_READ("JOHN").
	SMART(X) :- PEOPLE(X), CAN_READ(X).

	EXCITING_LIFE(_):- PEOPLE(X),HAPPY(X).

GOAL
	PEOPLE(X),EXCITING_LIFE(_).
